version: 2
jobs:
  install:
    docker:
      - image: circleci/node:7.10
    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

     # Persist everything to make sure we can run the tests in a separate job
      - persist_to_workspace:
          root: ~/repo
          paths:
              - ./
  test:
      docker:
        - image: circleci/node:7.10
      working_directory: ~/repo

      steps:
          # Attach workspace with everything in it to run the tests
          - attach_workspace:
              at: ./
          # run tests!
          - run: npm test

workflows:
  version: 2
  install-test:
    jobs:
      - install
      - test:
          requires:
            - install
